In [1]:
import numpy as np 

In [8]:
myarr

(array([[1, 2, 3, 4, 5, 6]]), numpy.int8)

In [4]:
myarr[0]

array([[1, 2, 3, 4, 5, 6]])

In [7]:
myarr[0,1]

TypeError: tuple indices must be integers or slices, not tuple

In [8]:

​myarr

(array([[1, 2, 3, 4, 5, 6]]), numpy.int8)

In [ ]:
array([[1, 2, 3, 4, 5, 6]]), numpy.int8)

In [9]:
myarr= np.array([[1,2,3,4,5,6]], np.int8)

In [10]:
myarr[0,2]

3

In [11]:
myarr.shape

(1, 6)

In [12]:
myarr.dtype

dtype('int8')

In [13]:
myarr[0,4]= 12

In [14]:
myarr

array([[ 1,  2,  3,  4, 12,  6]], dtype=int8)

In [15]:
listarray=np.array([[1,2,3],[5,6,7],[6,8,9]])

In [16]:
listarray

array([[1, 2, 3],
       [5, 6, 7],
       [6, 8, 9]])

In [17]:
listarray.size

9

In [18]:
listarray.shape 

(3, 3)

In [19]:
listarray.dtype

dtype('int32')

In [20]:
zeros=np.zeros((12,16))

In [21]:
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
zeros.dtype

dtype('float64')

In [24]:
rng=np.arange(20)

In [25]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
lspace = np.linspace(1,20,10)

In [27]:
lspace

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [30]:
emp = np.empty((4,8))

In [31]:
emp

array([[1.18303319e-311, 1.06224114e-321, 0.00000000e+000,
        0.00000000e+000, 3.96825235e-304, 5.02034658e+175,
        3.40920389e-057, 8.46727482e+165],
       [4.08374202e-033, 3.56777188e-057, 7.79013416e-043,
        7.74955420e-144, 3.59751658e+252, 1.46901661e+179,
        8.37404147e+242, 2.59027926e-144],
       [3.80985069e+180, 1.14428494e+243, 2.59027907e-144,
        7.79952704e-143, 1.14376585e-071, 8.32411392e-071,
        6.23466225e+174, 3.89278234e-033],
       [2.59027903e-144, 2.59903818e-144, 7.72819859e-091,
        9.07028193e-043, 1.14460339e-071, 1.11475752e+261,
        1.16318408e-028, 4.86670253e-051]])

In [32]:
ide=np.identity(20)

In [33]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [34]:
ide.shape

(20, 20)

In [35]:
ide.dtype

dtype('float64')

In [36]:
ide.size

400

In [37]:
arr=np.arange(99)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [40]:
arr.reshape(9,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
       [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [41]:
arr.reshape(11,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [43]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [44]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [45]:
ar=np.array(x)

In [46]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [48]:
ar.sum(axis=0)

array([12,  8,  9])

In [49]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [50]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [51]:
ar.flat

In [52]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [53]:
ar.ndim

2

In [54]:
ar.size

9

In [55]:
ar.nbytes

36

In [56]:
one=np.array([1,3,4,634,2])

In [57]:
one.argmax()

3

In [58]:
one.argmin()

0

In [59]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [60]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [61]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [62]:
ar.argmin()

8

In [63]:
ar.argmax()

6

In [65]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [66]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [68]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [71]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [74]:
ar2=np.array([[1,2,3],[3,2,7],[4,5,8]])

In [75]:
ar+ar2

array([[ 2,  4,  6],
       [ 7,  7, 13],
       [11,  6,  8]])

In [76]:
ar2

array([[1, 2, 3],
       [3, 2, 7],
       [4, 5, 8]])

In [77]:
ar*ar2

array([[ 1,  4,  9],
       [12, 10, 42],
       [28,  5,  0]])

In [78]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [79]:
ar.sum()

29

In [80]:
ar.min()

0

In [81]:
ar.max()

7

In [83]:
type(np.where(ar2>5))

tuple

In [84]:
np.count_nonzero(ar2)

9

In [85]:
import sys

In [91]:
py_ar = (0,4,55,2)

In [92]:
np_ar = np.array(py_ar)

In [93]:
sys.getsizeof(2) * len(py_ar)

112

In [94]:
np_ar.itemsize * np_ar.size

16

In [95]:
np_ar.tolist()

[0, 4, 55, 2]

In [96]:
pwd

'C:\\Users\\tanis'